
spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  #url: ${DatabaseUrl}
  #username: ${dbUsername}
  #password: ${dbPassword}
  url: "jdbc:mysql://localhost:3306/tenniskamu"
  username: "tenniskamu"
  password: "tenniskamu"
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect
 data:
  rest:
   base-path: /api
